trainer: score_distillation
distribution_loss: dmd

generator_ckpt: ./logs/ode_init/checkpoint_model_006000/model.pt

use_custom_teacher: true
teacher_ckpt_path: ./checkpoints/teacher.ckpt
base_wan_path: ../models/Wan-AI/Wan2.1-T2V-1.3B

real_name: Custom-RaCam-Teacher
fake_name: Wan2.1-T2V-1.3B

generator_fsdp_wrap_strategy: size
real_score_fsdp_wrap_strategy: size
fake_score_fsdp_wrap_strategy: size
text_encoder_fsdp_wrap_strategy: size

generator_cpu_offload: false
real_score_cpu_offload: false
fake_score_cpu_offload: false
text_encoder_cpu_offload: false
vae_cpu_offload: false

# ===== Data Settings =====
use_custom_data: true

dataset_root: ../data/InteriorGS-360video
split_json: ../data/train_test_split.json
frames_subdir: pano_camera0
max_frames: 800
frame_ext: png

steps_per_epoch: 200000
batch_fetch: 16

re_scale_pose: fixed:1.0  # Options: 'none' | 'unit_median' | 'fixed:<float>'

height: 480
width: 960
num_frames: 81
image_or_video_shape:
- 1      # batch size (will be set at runtime)
- 21     # latent frames (81 frames / 4 temporal compression)
- 16     # latent channels
- 60     # latent height (480 / 8 spatial compression)
- 120    # latent width (960 / 8 spatial compression)

# ===== Denoising Settings =====
denoising_step_list:
- 1000
- 750
- 500
- 250
warp_denoising_step: true
ts_schedule: false
num_train_timestep: 1000
timestep_shift: 5.0

guidance_scale: 3.0
real_guidance_scale: 3.0
fake_guidance_scale: 0.0
denoising_loss_type: flow

lr: 2.0e-06
lr_critic: 8.0e-07
beta1: 0.0
beta2: 0.999
beta1_critic: 0.0
beta2_critic: 0.999
weight_decay: 0.01
max_grad_norm_generator: 10.0
max_grad_norm_critic: 10.0

batch_size: 1
total_batch_size: 64

mixed_precision: true
gradient_checkpointing: true
sharding_strategy: full

num_frame_per_block: 3
same_step_across_blocks: true
independent_first_frame: false
last_step_only: false
num_training_frames: 21
causal: true

context_noise: 0

ema_weight: 0.99
ema_start_step: 200

log_iters: 50
gc_interval: 100
seed: 0

negative_prompt: '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走'

dfake_gen_update_ratio: 10

model_kwargs:
  timestep_shift: 5.0

wandb_host: https://api.wandb.ai
wandb_key:
wandb_entity:
wandb_project:

load_raw_video: false
i2v: false
no_save: false
no_visualize: true

debug: false

